basePath: /api/v1
definitions:
  server.ErrorJson:
    properties:
      error:
        $ref: '#/definitions/server.ErrorJsonBody'
        type: object
    type: object
  server.ErrorJsonBody:
    properties:
      message:
        type: string
    type: object
  server.UploadAudioResp:
    properties:
      file_name:
        type: string
      id:
        type: string
      track_id:
        type: string
      transcoder_id:
        type: string
    type: object
  server.UploadRawResp:
    properties:
      cid:
        type: string
    type: object
  server.UploadStatusResp:
    properties:
      id:
        type: string
      percentage:
        type: string
    type: object
host: localhost:1347
info:
  contact:
    email: hello@bitsong.io
    name: BitSong
  description: Swagger documentation for the BitSong Media Server service API.
  license:
    name: CC0
    url: https://creativecommons.org/share-your-work/public-domain/cc0/
  title: bitsongms API Docs
  version: "0.1"
paths:
  /upload/{id}/status:
    get:
      description: Get upload status by ID.
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.UploadStatusResp'
        "400":
          description: Failure to parse the id
          schema:
            $ref: '#/definitions/server.ErrorJson'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/server.ErrorJson'
      summary: Get upload status
      tags:
      - upload
  /upload/audio:
    post:
      description: Upload, transcode and publish to ipfs an audio
      parameters:
      - description: Audio file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.UploadAudioResp'
        "400":
          description: Error
          schema:
            $ref: '#/definitions/server.ErrorJson'
      summary: Upload and transcode audio file
      tags:
      - upload
  /upload/image:
    post:
      description: Upload, create and publish to ipfs an image
      parameters:
      - description: Image file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.UploadRawResp'
        "400":
          description: Error
          schema:
            $ref: '#/definitions/server.ErrorJson'
      summary: Upload and create image file
      tags:
      - upload
  /upload/raw:
    post:
      description: Upload, create and publish to ipfs a raw data
      parameters:
      - description: Raw data
        in: formData
        name: raw
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.UploadRawResp'
        "400":
          description: Error
          schema:
            $ref: '#/definitions/server.ErrorJson'
      summary: Upload and create raw data
      tags:
      - upload
swagger: "2.0"
